

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/components/**/*.{js,vue,ts}",
    "./app/layouts/**/*.vue",
    "./app/pages/**/*.vue",
    "./app/plugins/**/*.{js,ts}",
    "./app/app.vue",
    "./app/error.vue",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary": "#303032",
        "on-tertiary-fixed-variant": "#4b4544",
        "on-error": "#690005",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#5f5e60",
        "secondary": "#4ae183",
        "surface-container": "#201f1f",
        "on-background": "#e5e2e1",
        "surface-container-high": "#2b2a2a",
        "on-tertiary": "#342f2e",
        "on-surface-variant": "#c8c6ca",
        "on-tertiary-fixed": "#1f1b19",
        "on-secondary-fixed": "#00210c",
        "inverse-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "surface": "#141313",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-primary-container": "#7e7d7f",
        "error": "#ffb4ab",
        "surface-variant": "#353434",
        "tertiary-container": "#151110",
        "on-tertiary-container": "#837c7a",
        "on-secondary-fixed-variant": "#005228",
        "on-secondary-container": "#00431f",
        "tertiary-fixed": "#eae0de",
        "background": "#141313",
        "surface-dim": "#141313",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#003919",
        "surface-container-highest": "#353434",
        "primary-container": "#121214",
        "primary-fixed-dim": "#c8c6c8",
        "on-primary-fixed": "#1b1b1d",
        "primary": "#c8c6c8",
        "surface-bright": "#3a3939",
        "tertiary-fixed-dim": "#cec4c2",
        "secondary-container": "#06bb63",
        "primary-fixed": "#e5e1e4",
        "surface-tint": "#c8c6c8",
        "on-primary-fixed-variant": "#474649",
        "secondary-fixed-dim": "#4ae183",
        "on-surface": "#e5e2e1",
        "tertiary": "#cec4c2",
        "secondary-fixed": "#6bfe9c",
        "outline-variant": "#47464a",
        "outline": "#919095",

        // Add our extracted custom dashboard colors
        "dash-primary": "#161d85",
        "dash-primary-text": "#ffffff",
        "dash-secondary": "#ff6100",
        "dash-secondary-variant": "#d65200",
        "dash-secondary-bg": "rgba(255, 97, 0, 0.1)",
        "dash-tertiary": "#2632aa",
        "dash-bg": "#020044",
        "dash-surface": "#161d77",
        "dash-surface-container": "#171d7b",
        "dash-surface-variant": "#151d82",
        "dash-border": "#1a27aa",
        "dash-border-variant": "#2530a3",
        "dash-text-muted": "#a0a0a0",
        "dash-text-dim": "#707070",
        "dash-danger": "#ff4040",
        "dash-warning": "#ffaa00",
        "dash-caution": "#ffff00"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "stack-md": "16px",
        "margin": "32px",
        "panel-padding": "24px",
        "gutter": "24px",
        "stack-lg": "32px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "display-md": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "data-mono": ["Inter"],
        "label-caps": ["Inter"]
      },
      fontSize: {
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-md": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "data-mono": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
