NAME2URL = {
    "boulder_k_index_1m": "https://services.swpc.noaa.gov/json/boulder_k_index_1m.json",
    "planetary_k_index_1m": "https://services.swpc.noaa.gov/json/planetary_k_index_1m.json",
    "satellite-longitudes": "https://services.swpc.noaa.gov/json/goes/satellite-longitudes.json",
    "magnetometers-1-day": "https://services.swpc.noaa.gov/json/goes/primary/magnetometers-1-day.json",
    "primary-differential-electrons-1-day": "https://services.swpc.noaa.gov/json/goes/primary/differential-electrons-1-day.json",
    "primary-differential-protons-1-day": "https://services.swpc.noaa.gov/json/goes/primary/differential-protons-1-day.json",
    "primary-integral-electrons-1-day": "https://services.swpc.noaa.gov/json/goes/primary/integral-electrons-1-day.json",
    "primary-integral-protons-1-day": "https://services.swpc.noaa.gov/json/goes/primary/integral-protons-1-day.json",
    "primary-xray-1-day": "https://services.swpc.noaa.gov/json/goes/primary/xrays-1-day.json",
    "secondary-differential-electrons-1-day": "https://services.swpc.noaa.gov/json/goes/secondary/differential-electrons-1-day.json",
    "secondary-differential-protons-1-day": "https://services.swpc.noaa.gov/json/goes/secondary/differential-protons-1-day.json",
    "secondary-integral-electrons-1-day": "https://services.swpc.noaa.gov/json/goes/secondary/integral-electrons-1-day.json",
    "secondary-integral-protons-1-day": "https://services.swpc.noaa.gov/json/goes/secondary/integral-protons-1-day.json",
    "secondary-xray-1-day": "https://services.swpc.noaa.gov/json/goes/secondary/xrays-1-day.json",
    "observed-solar-cycle-indices": "https://services.swpc.noaa.gov/json/solar-cycle/observed-solar-cycle-indices.json",
    "f10-7cm-flux": "https://services.swpc.noaa.gov/json/solar-cycle/f10-7cm-flux.json",
    "predicted-solar-cycle": "https://services.swpc.noaa.gov/json/solar-cycle/predicted-solar-cycle.json",
    "solar_regions": "https://services.swpc.noaa.gov/json/solar_regions.json",
    "solar-radio-flux": "https://services.swpc.noaa.gov/json/solar-radio-flux.json",
    "dscovr_mag_1s": "https://services.swpc.noaa.gov/json/dscovr/dscovr_mag_1s.json"
}